Name: NU803-0.COM
Type: file
Size: 131072
Last-Modified: '1993-03-08T13:30:16Z'
SHA-1: 7A4C4B665237DFC3EC2DC77AFB2CC3A5A78D8B57
Description: |
  Famicom ROM for Battletoads & Double Dragon.
  Retail version (USA). Verified on No-Intro.
  Missing iNES header. Once the first 16 bytes
  are spliced from the No-Intro dump, the hash matches.
  SHA-1: 61832D0F955CFF169FF059BD557BE4F522B15B7C
  Fragmented file, must be concatenated.
